### ISSUE TITLE
Dead end on input

### ISSUE THREAD

**Issue by szepeviktor** [10up/safe-redirect-manager#104]
Could we have a link to the rule list in the `Redirect rule updated/published.` notice?

**Comment by tlovett1** [comment]
Definitely. Can you write a PR?

**Comment by szepeviktor** [comment]
I would add the link this way for "published" and "'updated":
```php
sprintf( __( 'Redirect rule updated. <a href="%s">Back to rules</a>', 'safe-redirect-manager' ), esc_url( admin_url( 'edit.php?post_type=redirect_rule' ) ) )
```
Problems:
- breaks translations
- contains HTML

Could you help me?

**Comment by szepeviktor** [comment]
> contains HTML

Coudl be solved by
```php
$back_html = sprintf( '<a href="%s">%s</a>', esc_url( admin_url( 'edit.php?post_type=redirect_rule' ) ), __( 'Back to rules', 'safe-redirect-manager' ) );
```

**Comment by szepeviktor** [comment]
But is still breaks translations: `Redirect rule updated. %s`
Maybe concatenating strings?
```php
__( 'Redirect rule updated.', 'safe-redirect-manager' ) . $back_html
```

**Comment by szepeviktor** [comment]
Thank you.
