### ISSUE TITLE
Oudated french translation

### ISSUE THREAD

**Issue by benoitchantre** [10up/safe-redirect-manager#128]
With WordPress 4.6, the loading priority of mo files has changed.

If people use an older version of WordPress, the mo file inside the plugin directory will be used instead of the language pack from translate.wordpress.org. WordPress can download language packs for plugins since December 5, 2015.

The french translation is now validated and WordPress can download the language pack automatically.
I think we can safely remove the french translation files from the plugin to avoid the user with WordPress < 4.6 to have an incomplete translation.

I can do a PR.

**Comment by jeffpaul** [comment]
@hrkhal thanks for the feedback, its greatly appreciated!  I'd welcome a related PR on this if you still have interest and availability... thanks again!

**Comment by benoitchantre** [comment]
@jeffpaul There's already a PR (#129) that removes the outdated french translation. It's title could have been better.

**Comment by jeffpaul** [comment]
Closed via #129
