### ISSUE TITLE
Redirect Limits

### ISSUE THREAD

**Issue by jilltilt** [10up/safe-redirect-manager#145]
How can we change the default of 250 redirects in the updated version? The old code hack does not work anymore (https://www.isrgrajan.com/how-to-increase-redirect-limits-in-safe-redirect-manager-wordpress-plugin.html)
Please help!

**Comment by grappler** [comment]
It seems the article has been updated to the latest version. This issue could be closed.

**Comment by yeevy** [comment]
I've run into issues relating to this recently.

If you use the WP CLI to import from a .csv file it bypasses the limit _but_ the issue still stands that when it's checking for the redirects, it only loads 250 from the DB.

To fix this completely you can add some code to `functions.php` to set a custom limit. 

Note: You will need to remove the specific transient cache stuff from the `wp_options` table as it's a serialised version of the redirects used for caching. If you don't remove it then it will appear that your new limit isn't being used. (I don't have a copy of the SQL query I used to find it but you're looking for a single row which then will need removing from the table)

```
<?php

/* add to your functions.php */

add_filter( 'srm_max_redirects', 'custom_srm_max_redirects' );
function custom_srm_max_redirects() {
	return 1000; /* Specific override to make sure we get all the Redirect values we're after */
};
```

**Comment by scheinercc** [comment]
@yeevy thanks! that worked like a charm :) the `option_name` is `_transient__srm_redirects` and it was enough for me to empty the `option_value`. On the next click on "Create Redirect Rule" the value was set again.

**Comment by ciprianimike** [comment]
this worked really well, even without deleting the `_transient__srm_redirects` option

**Comment by TheLastCicada** [comment]
I would also question why we still have the 250 limit.  It seems like this is a bit antiquated and we could greatly increase this without danger.
