### ISSUE TITLE
create_function() deprecated in PHP 7.2.2

### ISSUE THREAD

**Issue by bengreeley** [10up/safe-redirect-manager#150]
In PHP 7.2.2 the function create_function() has been deprecated, which is used on the following line.

https://github.com/tlovett1/safe-redirect-manager/blob/93ffb3af353c07b70288932cabc65e00f103b6f2/inc/classes/class-srm-post-type.php#L163

This should be converted to an anonymous function. Will submit a PR if I have time today, but wanted to flag this while it was on my mind.

**Comment by tlovett1** [comment]
Thanks @bengreeley ! Would love a PR but let's not do anonymous function since this plugin is 5.2 compat.

**Comment by tomjn** [comment]
This is fixed by #147 once it gets merged

**Comment by pattonwebz** [comment]
Fix for this has been merged in at https://github.com/10up/safe-redirect-manager/commit/271980712aa2c837a6f5f2ba8b0eabaeeeac0f8c

**Comment by TomasVotruba** [comment]
If you even need to upgrade more `create_function` cases, [Rector does it pretty well](https://github.com/rectorphp/rector/commit/3376254f7742abab3fde0a865ae4de8a420e964f).

**Comment by lkraav** [comment]
> Fix for this has been merged in at 2719807

Hmm, how come this issue has never been closed, I wonder.

**Comment by TomasVotruba** [comment]
@lkraav The PR needs to contain ["closes"](https://help.github.com/articles/closing-issues-using-keywords/) keyword in description/commit message. Without that, Github doesn't care.

**Comment by lkraav** [comment]
I meant "this project is alive, has active human maintainer oversight, too" but maybe not enough resource for issue gardening.

**Comment by TomasVotruba** [comment]
This doesn't need maintainer, just keyword in PR.

**Comment by tlovett1** [comment]
Hey all, we are absolutely maintaining this project!

Closing.
