### ISSUE TITLE
Doesn't work with .html extensions?

### ISSUE THREAD

**Issue by partounian** [10up/safe-redirect-manager#152]
Trying to redirect `/Contact.html` to `/contact` throws a 404, seems to affect all redirects that end in a .html. Is this a known problem?

P.S. I'm using Trellis and Bedrock

**Comment by austinpray** [comment]
I'm pretty certain this is caused by the nginx config not passing these .html requests to php-fpm. I would expect .jpg and .png redirects to be broken in a similar way.

Dump your nginx config here?

**Comment by jeffpaul** [comment]
@partounian per @austinpray's note, could you shared your nginx config?

@austinpray thanks for helping out, it's much appreciated!
