### ISSUE TITLE
Wildcard doesn't match zero characters

### ISSUE THREAD

**Issue by GaryJones** [10up/safe-redirect-manager#156]
Given the following:

- Redirect From: `foo/*`
- Redirect To: `https://example.com/bar/*`

Results in:

1. `https://example.com/foo/baz` correctly redirects to `https://example.com/bar/baz`. i.e. `*` matches `baz`
2. `https://example.com/foo/` fails to redirect to the expected `https://example.com/bar/` i.e. `*` matches `{empty string}`.

The expected behaviour is that the wildcard could be an empty string.

The unit tests do NOT cover this use case.

The current workaround is to add a second redirect rule without the wildcard, which works:

- Redirect From: `foo/`
- Redirect To: `https://example.com/bar/`

**Comment by brettshumaker** [comment]
Related #136

**Comment by GaryJones** [comment]
I added the following unit test, to emulate the desired behaviour, where a redirect from `/one/*` to `/gohere/*` will work for a requested URL of `/one/`:

```php
	/**
	 * Test handle empty wildcards
	 *
	 * @since 1.9.1
	 */
	public function testHandleEmptyWildcard() {
		$_SERVER['REQUEST_URI'] = '/one/';
		$redirected             = false;
		$redirect_to            = '/gohere/*';
		srm_create_redirect( '/one/*', $redirect_to );

		add_action(
			'srm_do_redirect', function( $requested_path, $redirected_to, $status_code ) use ( &$redirect_to, &$redirected ) {
				if ( $redirected_to === '/gohere/' ) {
					$redirected = true;
				}
			}, 10, 3
		);

		SRM_Redirect::factory()->maybe_redirect();

		$this->assertTrue( $redirected );
	}
```

----

The issue seems to be related to the `untrailingslashit()` at https://github.com/10up/safe-redirect-manager/blob/9fc66f2d9acf39ad2af9a42bc3d4865907b23608/inc/classes/class-srm-redirect.php#L69

With the above unit test, the requested URL of `/one/` gets changed to `/one`. This results in all `$matched_path` comparisons being false, and so the [condition here](https://github.com/10up/safe-redirect-manager/blob/9fc66f2d9acf39ad2af9a42bc3d4865907b23608/inc/classes/class-srm-redirect.php#L142) doesn't pass, and no redirect is done.

So why is the `untrailingslashit()` there?

With it removed, one of the many assertions in the `testTrailingSlashes()` test method fails. https://github.com/10up/safe-redirect-manager/blob/9fc66f2d9acf39ad2af9a42bc3d4865907b23608/tests/test-core.php#L199-L214

This is testing the behaviour that a redirect from `/one` to `/gohere` will work for a URL of `/one/`. This is not unreasonable behaviour - an old bookmark may hit the site at `/one/`, and the redirect should still work, without having to resort to slashed and unslashed rules or regex rules.

I've not yet got a working solution to account for both behaviours.
