### ISSUE TITLE
wp cli breaking change in current version (1.9.1)

### ISSUE THREAD

**Issue by mariolukas** [10up/safe-redirect-manager#158]
Setup:
wp-cli : 1.4.1
php: 5.5.9
wordpress:  4.9.8

I just installed version 1.9.1. Now i get the following errors when i run wp cli for safe-redirect-manager. 

     PHP Parse error:  syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /var/www/html/wp-content/plugins/safe-redirect-manager/inc/classes/class-srm-wp-cli.php on line 19
     Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in /var/www/html/wp-content/plugins/safe-redirect-manager/inc/classes/class-srm-wp-cli.php on line 19

The related change is located here: 
https://github.com/10up/safe-redirect-manager/blob/master/inc/classes/class-srm-wp-cli.php#L19

`list()` is a reserved keyword in php. (see http://www.php.net/manual/en/reserved.keywords.php)
It should be renamed back to `_list()` to make it woking again.

**Comment by tlovett1** [comment]
Thanks for the report! Fixed in 1.9.2.
