### ISSUE TITLE
Update Failed: The update cannot be installed because we will be unable to copy some files.

### ISSUE THREAD

**Issue by cromieent** [10up/safe-redirect-manager#159]
Hello,

I am trying to use the auto-update feature in the plugins admin section and it is not allowing me to because of the following error:

Update Failed: The update cannot be installed because we will be unable to copy some files. This is usually due to inconsistent file permissions.

Two questions:  
1) Which permissions to which directories does it need?
2) If I can't modify the permissions, do you recommend manually installing the update?

Thanks,

Scott Cromie
Cromie Enterprises, LLC

**Comment by tlovett1** [comment]
If the auto install fails, we recommend manually copying the files.
