### ISSUE TITLE
PHP Warning preg_match(): Compilation failed: nothing to repeat at offset 75

### ISSUE THREAD

**Issue by josephfusco** [10up/safe-redirect-manager#164]
PHP Warning: preg_match(): Compilation failed: nothing to repeat at offset 75 in .../wp-content/plugins/safe-redirect-manager/inc/classes/class-srm-redirect.php on line 127

This is on a multisite running PHP 7.2

**Comment by jeffpaul** [comment]
@josephfusco thanks for the feedback, it's greatly appreciated!  Can you confirm the WordPress version and any other installed/active plugins and themes to help us troubleshoot and resolve?

**Comment by josephfusco** [comment]
@jeffpaul thanks for the quick reply!

This site is using WordPress 5.1.1.

I was able to reproduce this with the Twenty Seventeen default theme with no plugins active other than safe-redirect-manager & query-monitor.

After going through all of the redirect entries for the site this was happening on, I was able to identify that this was being thrown from 1 redirect in particular which contained invalid regex.

"Nothing to repeat at offset 75" was because the invalid regex appeared at the 75th character in the **Redirect From:** string.

**Comment by josephfusco** [comment]
I think having a more descriptive error thrown for invalid regex would be sufficient to help others who may run into this warning.

Maybe a future version of this plugin can have inline regex pattern validation to help mitigate an invalid entry but that wouldn't prevent an import with bad data like in my own case.

Overall this plugin has been a delight to use & thank you for your work on this.

**Comment by jeffpaul** [comment]
@josephfusco we require PHP 7.4, can you confirm if this is still occurring on that version of PHP?
