### ISSUE TITLE
[Suggestion/Idea] Open to a new tab

### ISSUE THREAD

**Issue by reSailorMac** [10up/safe-redirect-manager#167]
Is there any way you can add the option for the new redirected link to open into a new tab rather using the same page?

**Comment by jeffpaul** [comment]
@reSailorMac can you please clarify the use case you have here?

**Comment by barryceelen** [comment]
@reSailorMac @jeffpaul Opening a new tab or browser window is not possible when redirecting.

Opening links in a new tab can only be achieved in the HTML document itself, eg. by adding a [target attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target) to the anchor tag:

`<a href="/my-awesome-page" target="_blank">This link opens in a new tab or page</a>`
