### ISSUE TITLE
Redirect loop detection

### ISSUE THREAD

**Issue by noesteijver** [10up/safe-redirect-manager#174]
Hello,

I've activated the redirect loop detection.

After that, I've added two redirects that should create a loop. And when visiting one of the two pages, I get stuck in a loop.

My questions:
- What should the loop detection do? 
- Should it give a message when you add a new redirect that causes a loop? 
- Or should it interrupt a loop when it's happening?

Hopefully you can help me out. Thanks in advance!
-Kevin

**Comment by noesteijver** [comment]
Hello,

I see that a fix has been made. When will this be available as an official new version?

-Kevin

**Comment by jeffpaul** [comment]
@noesteijver there's no immediate PR in this repo that resolves this, though possibly @jameswburke @renatonascalves might share a PR here that they've appeared to merge into their downstream repo?  If so, then we can look into reviewing/merging that in an upcoming Safe Redirect Manager release.

**Comment by dinhtungdu** [comment]
The loop detection feature is included in the official release already. Once enabled by using [a filter](https://github.com/10up/safe-redirect-manager#redirect-loops), a notice will display on the top of the redirect list if a potential loop is detected.
![image](https://user-images.githubusercontent.com/5423135/99474674-973ee900-297f-11eb-8df8-332072e0bb35.png)
