### ISSUE TITLE
Add option to ignore query params

### ISSUE THREAD

**Issue by braders** [10up/safe-redirect-manager#189]
**Describe the bug**
On sites with pretty permalinks enabled, query strings are almost never considered a proper part of the URL, and would be expected to be ignored when looking for redirect matches.

**Steps to Reproduce**
Create a redirect from `/page1/` to `/page2/`.

On navigating to `/page1/` the plugin redirects correctly.
On navigating to `/page1/?param` the plugin does not redirect.

This is causing us significant issues because users are hitting our page to be redirected from Adword links and social media, where various marketting paramaters are included (gclid, utm_source etc). In many cases an option would be to alter the redirect to `/page1/*`, but this doesn't work in cases where the child pages are to stay accessible. (i.e. where you want to redirect `/page1/` without affecting `/page1/child`.

**Expected behavior**
I would expect `/page1/?param` to redirect to `/page2/`.

(It may be necessary to make this behaviour optional to handle sites which are not using pretty permalinks).

**Workaround**

The following regular expression can be used ("Enable Regular Expressions" must be ticked)

`^\/page1(\/)?(\?.*)?$`

**Additional context**

I can see a few ways of resolving this:
- Add a checkbox to the UI labelled something like "Ignore query strings".
- Add a filter to the `maybe_redirect` function to enable ignore query string functionality
- Add a filter allowing a blacklist of query strings to be ignored to be created.

If the query strings are ignored they should be passed on to the redirect-to path, in order to maintain analytics attribution.

The second option above would be my preference. Is this something which is likely to be fixed? If necessary I can contribute a pull request, but it would be nice to have an indication of the preferred way to handle this before I start.

**Comment by jeffpaul** [comment]
@braders welcome to Safe Redirect Manager and thanks for your feedback!  One question I have as we review this for how we might handle things is you note your Expected Behavior to be:
I would expect `/page1/?param` to redirect to `/page2/`.

Is there a case where you'd want that to be the following?:
I would expect `/page1/?param` to redirect to `/page2/?param`.

**Comment by braders** [comment]
@jeffpaul Thanks for your response! As suggested in the potential solutions I do think that it would be beneficial to maintain the query strings (i.e. to redirect to `/page2/?param`) in order to maintain analytics attribution parameters. Sorry that this was not clear in the expected behaviour.

Whilst maintaining the query params sounds like a good default, there may be cases where users would want to disable this - e.g. in cases where pretty permalinks are not in use (although to be honest, I've not actually tested to see if SRM supports installations where pretty permalinks are not in use).

**Comment by jeffpaul** [comment]
@braders thanks for the update, I've updated this to an `enhancement` and added to our `Future Release` milestone (mainly due to it having a workaround).  If you're able to work on a PR, then I'd be happy to get that through review and into any upcoming release.
