### ISSUE TITLE
Custom WP_Importer

### ISSUE THREAD

**Issue by stevegrunwell** [10up/safe-redirect-manager#97]
It would be nice to have a custom WP_Importer implementation (Tools > Import) for bulk-importing redirects via CSV. The `import_file()` method would be responsible for most of the logic, but this would allow sites with limited/no WP-CLI access to import sites without involving their hosts.

**Comment by intrepidws** [comment]
This would be amazingly helpful. I've got 1500+ redirects that I need to get in place somehow and I'm dreading it.

**Comment by stevegrunwell** [comment]
@intrepidws if you need those redirects in place ahead of this feature getting developed and have access to WP-CLI on your site, I'd suggest you take a look at the [`wp safe-redirect-manager import` WP-CLI command](https://github.com/tlovett1/Safe-Redirect-Manager/blob/master/inc/wp-cli.php#L179) that's already included with the plugin ;)

**Comment by tlovett1** [comment]
I'd be up for this one.

**Comment by YesThatAllen** [comment]
`wp safe-redirect-manager import path/to/my/file.csv` worked great for me.

@stevegrunwell Thanks for the pointer!

**Comment by ryanhellyer** [comment]
Related to this, I think an example .csv file would be good too. I needed to import some redirects urgently, and couldn't figure out what format the CSV file needed to be in fast enough, so ended up just writing my own importer from scratch. A simple example file showing what needs to go where probably would have solved that issue.

**Comment by planetahuevo** [comment]
You can find an example here:
https://github.com/10up/safe-redirect-manager/blob/master/inc/classes/class-srm-wp-cli.php
`* <file>
	 * : Path to one or more valid CSV file for import. This file should contain
	 * redirection from and to URLs, regex flag and HTTP redirection code. Here
	 * is example table:
	 *
	 * | source                     | target             | regex | code | order |
	 * |----------------------------|--------------------|-------|------|-------|
	 * | /legacy-url                | /new-url           | 0     | 301  | 0     |
	 * | /category-1                | /new-category-slug | 0     | 302  | 1     |
	 * | /tes?t/[0-9]+/path/[^/]+/? | /go/here           | 1     | 302  | 3     |
	 * | ...                        | ...                | ...   | ...  | ...   |
	 *
	 * You can also use exported redirects from "Redirection" plugin, which you
	 * can download here: /wp-admin/tools.php?page=redirection.php&sub=modules`
