### ISSUE TITLE
Quick Edit and Bulk Edit

### ISSUE THREAD

**Issue by espellcaste** [10up/safe-redirect-manager#98]
An idea for the plugin, maybe I'll create a PR in the coming days.

When you already have several redirections created but they are with the "wrong" HTTP Status Code, you have to manually to change them.

I suggest adding a quick edit and also a bulk edit to the plugin to make it easier to edit in bulk several redirections at once.

**Comment by tlovett1** [comment]
That would be great. PR would be appreciated.

**Comment by espellcaste** [comment]
PR soon! Working on it! ;)

**Comment by jeffpaul** [comment]
@amyevans @jameswburke did you have a downstream fix for this that could be shared?

**Comment by amyevans** [comment]
Nope, sorry! Not entirely sure what happened with that merge that's referenced, but it was definitely unrelated to this issue.
